--Done by AISHWARYA
--BOOKSDATABASE
create Database BOOKSDATABASE
use BOOKSDATABASE

--BOOKS TABLE
create table BOOKSTABLE(BID INT PRIMARY KEY,BNAME VARCHAR(20) NOT NULL,PRICE SMALLMONEY NOT NULL,PUBLISHDATE DATETIME NOT NULL)
SP_HELP BOOKSTABLE

--CUSTOMERS TABLE
DROP TABLE CUSTOMERSTABLE
CREATE TABLE CUSTOMERSTABLE(CID INT PRIMARY KEY,CNAME VARCHAR(20) NOT NULL,BID INT FOREIGN KEY REFERENCES BOOKSTABLE(BID))
SP_HELP CUSTOMERSTABLE

--AUTHORS TABLE
CREATE TABLE AUTHORSTABLE(BID INT FOREIGN KEY REFERENCES BOOKSTABLE(BID),ANAME VARCHAR(20)NOT NULL,AID INT)
SP_HELP AUTHORSTABLE
-- UNIQUE INDEX FOR AUTHOR ID
CREATE UNIQUE INDEX ANO ON AUTHORSTABLE(AID)

begin TRANSACTION

INSERT INTO BOOKSTABLE VALUES(1,'C',120,'1978-02-22'),(2,'JAVA',350,'1995-08-01')

INSERT INTO CUSTOMERSTABLE VALUES(1001,'CITY',1),(1002,'TOWN',2)

INSERT INTO AUTHORSTABLE VALUES(1,'DENNIS RITCHIE',123),(2,'JAMES GOSLING',456)
COMMIT

-- 1)List the Books details which book have At least one author,one customer exists.
SELECT * FROM BOOKSTABLE WHERE EXISTS(SELECT ANAME,CNAME FROM AUTHORSTABLE,CUSTOMERSTABLE WHERE AUTHORSTABLE.BID=BOOKSTABLE.BID OR CUSTOMERSTABLE.BID=BOOKSTABLE.BID)

--2)List  the all Books,Authors,Customers details.
SELECT * FROM BOOKSTABLE FULL OUTER JOIN AUTHORSTABLE ON BOOKSTABLE.BID=AUTHORSTABLE.BID FULL OUTER JOIN CUSTOMERSTABLE ON BOOKSTABLE.BID=CUSTOMERSTABLE.BID

--3)To print the books details which books published date between ’01-dec-2019’ to ’04-apr-20’.
 SELECT *FROM BOOKSTABLE WHERE PUBLISHDATE BETWEEN '2019-12-01' AND '2020-04-04'

 --4)List the Books details Which book at least 3 or more customers.
 SELECT *FROM BOOKSTABLE WHERE EXISTS (SELECT 3 FROM CUSTOMERSTABLE WHERE BOOKSTABLE.BID=CUSTOMERSTABLE.BID)

 --5)List the Book details which book price is highest.
 SELECT *FROM BOOKSTABLE WHERE PRICE=(SELECT MAX(PRICE) FROM BOOKSTABLE)

 --6)List the Customer details which customer not taken any books.
 SELECT *FROM CUSTOMERSTABLE WHERE NOT EXISTS(SELECT *FROM BOOKSTABLE WHERE CUSTOMERSTABLE.BID=BOOKSTABLE.BID)

--8)To display the book names for given book id using  UDF[user defined function].
CREATE FUNCTION FUNC(@BID INT)
RETURNS VARCHAR(20)
AS
BEGIN
DECLARE @BN VARCHAR(20)
SELECT @BN=BNAME FROM BOOKSTABLE WHERE BID=@BID
RETURN @BN
END





